### ISSUE TITLE
Activity返回后报错

### ISSUE THREAD

**Issue by KennenH** [zhangxq/keyboardHeightProvider#2]
E/WindowManager: android.view.WindowLeaked: Activity com.example.schoolairdrop.ui.activity.ChatActivity has leaked window android.widget.PopupWindow$PopupViewContainer{1557c1fd V.E..... ......ID 0,0-0,926} that was originally added here
        at android.view.ViewRootImpl.<init>(ViewRootImpl.java:379)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:260)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:74)
        at android.widget.PopupWindow.invokePopup(PopupWindow.java:1122)
        at android.widget.PopupWindow.showAtLocation(PopupWindow.java:938)
        at android.widget.PopupWindow.showAtLocation(PopupWindow.java:902)
        at com.example.schoolairdrop.ui.utils.HeightProvider$1.run(HeightProvider.java:47)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5318)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:922)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:717)

public HeightProvider init() {
        if (!isShowing()) {
            final View view = mActivity.getWindow().getDecorView();
            // Delay loading popupwindow, if not, error will be reported
            view.post(new Runnable() {
                @Override
                public void run() {
                    showAtLocation(view, Gravity.NO_GRAVITY, 0, 0);//错误出在这里…
                }
            });
        }
        return this;
    }

**Comment by jashgopani** [comment]
### Problem
The HeightProvider's popup window is not closed properly , which is causing a memory leak !

### Solution
call `heightProvider.dismiss()` inside activity's `onDestroy()` method.
